### ISSUE TITLE
Broken gemspec for sass-embedded-1.77.0-x86_64

### ISSUE THREAD

**Issue by nathangibson** [sass-contrib/sass-embedded-host-ruby#206]
As of today with the release of 1.77.0 I get the following failure in my Gitlab pipeline: 
> bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
/usr/local/bundle/gems/sass-embedded-1.77.0-x86_64-linux/ext/sass/cli.rb:16:in `<top (required)>': The gemspec for sass-embedded at /usr/local/bundle/specifications/sass-embedded-1.77.0-x86_64-linux.gemspec was broken.
(gitlab-runner 16.11.0, docker image ruby:3.1.2 with jekyll 4.3.3)

In my local installation I have no trouble with sass-embedded-1.77.0-arm64-darwin.

By adding `gem 'sass-embedded', '> 1.54', '< 1.77'` to my Gemfile, I'm able to workaround this problem by having the pipeline use the previous version of sass-embedded.

Thanks for your work on this important gem!

**Comment by ntkme** [comment]
> ruby:3.1.2

You have a broken rubygems version 3.3.7 bundled with 3.1.2. This gem requires rubygems >=3.3.22 on linux platforms.  Please update to ruby 3.1.5, 3.2.4, 3.3.1, or later version.

**Comment by nathangibson** [comment]
> > ruby:3.1.2
> 
> You have a broken rubygems version 3.3.7 bundled with ruby 3.1.2. This gem requires rubygems >=3.3.22 on linux platforms. Please update to ruby 3.1.5, 3.2.4, 3.3.1, or later version.

Thanks so much!
