### ISSUE TITLE
Gem fails when trying to run on aarch64-linux-musl platform

### ISSUE THREAD

**Issue by Physium** [sass-contrib/sass-embedded-host-ruby#210]
I'm trying to run rails 7 on ruby-alphine docker image and face an issue when i try executing any rails commands

Error:
sass-embedded-1.77.0-aarch64-linux-musl/ext/sass/embedded_sass_pb.rb:11: [BUG] Segmentation fault at 0x0000000000003b60

Is this gem not supported for alphine?

**Comment by ntkme** [comment]
The crash is from `google-protobuf` gem, which is a dependency of this gem. It looks like the google-protobuf is having issue on musl.

What's the protobuf version you have? Can you provide output of `gem info google-protobuf`?

**Comment by ntkme** [comment]
This is a bug in google-protobuf, see https://github.com/protocolbuffers/protobuf/issues/16853 for details, as well as workaround.

**Comment by ntkme** [comment]
For `bundle`, the issue can be workaround by setting `force_ruby_platform=true` as following:

``` sh
apk add build-base
bundle config --local force_ruby_platform true
bundle install
```

**Comment by Physium** [comment]
Thanks! I have the workaround, just wondering if theres a way if I can get gems natively compiled based on the platform type. Will proceed with the workaround, thanks!

**Comment by ntkme** [comment]
> if theres a way if I can get gems natively compiled based on the platform type

The bug has been reported protobuf team, now we have to wait for them to fix it in future releases.

**Comment by ntkme** [comment]
Meanwhile, you can add this to `Gemfile` and force build from source only for `aarch64-linux-musl`:

``` ruby
gem 'google-protobuf', force_ruby_platform: true if Gem::Platform.local.to_s == 'aarch64-linux-musl'
```

**Comment by ntkme** [comment]
This now affects x86_64-linux-musl as well.

Workaround:

``` ruby
gem 'google-protobuf', force_ruby_platform: true if RUBY_PLATFORM.include?('linux-musl')
```
