### ISSUE TITLE
Byte order mark is first character of rendered CSS in some cases

### ISSUE THREAD

**Issue by nickpearson** [sass-contrib/sass-embedded-host-ruby#222]
Thank you for creating and maintaining this library. It's been very helpful in switching away from the sassc gem.

I came across a bug in my app that I tracked to this library. Some CSS escape sequences trigger a byte order mark character (`"\uFEFF"`) to be the first character of the rendered CSS output when calling `Sass.compile_string(...).css`. Here's a practical example of some CSS with such a sequence:

```scss
// add an opening double-quote character before the blockquote content
blockquote::before {
  content: "\301D";
}
```

And here's the simplest example I've found that triggers the bug:

```scss
a { b: "\0" }
```

From my testing, it only happens when the keyword arguments include `syntax: :scss` and `style: :compressed`:

```ruby
scss = 'a { b: "\0" }'
css = Sass.compile_string(scss, syntax: :scss, style: :compressed).css
css[0] == "\uFEFF" #=> true
```

The byte order mark is "invisible" in an irb session, but Chrome's DevTools shows it as a red bullet when viewing the compiled CSS in the Sources tab. (Browsers interpret the byte order mark as part of the file's first selector, making a `div` selector something like `•div`, meaning nothing will match that selector, which is how I knew there was a bug somewhere.)

After further inspection, when omitting the `style` keyword argument, the rendered CSS starts with `@charset "UTF-8";`, but this @ rule isn't included with `style: :compressed`, making me wonder if the byte order mark is appearing as part of the stripping of this rule.

In case it helps anyone else who comes across the same thing, I'm currently working around this by removing the byte order mark from the beginning of the rendered CSS string if it's present:

```ruby
def render_scss(scss)
  css = Sass.compile_string(scss, syntax: :scss, style: :compressed).css
  css = css[1..-1] if css[0] == "\uFEFF"
  css
end
```

If you can't work around it like this, you could include `/*!*/` at the beginning of your SCSS so that the byte order mark precedes the `/*!*/` in the output rather than being adjacent to (and breaking) your first selector. (The `/*!` comment prefix means "keep this comment, even in compressed mode.")

**Comment by ntkme** [comment]
You need to use `charset: false`. For example:

``` ruby
css = Sass.compile_string(scss, syntax: :scss, style: :compressed, charset: false).css
```

Quote from documentation - https://rubydoc.info/gems/sass-embedded/Sass

> charset (Boolean) — By default, if the CSS document contains non-ASCII characters, Sass adds a @charset declaration (in expanded output mode) or a byte-order mark (in compressed mode) to indicate its encoding to browsers or other consumers. If charset is false, these annotations are omitted.

**Comment by ntkme** [comment]
You need to add `charset: false` option to omit the BOM:

``` ruby
scss = 'a { b: "\0" }'
css = Sass.compile_string(scss, syntax: :scss, style: :compressed, charset: false).css
css[0] == "\uFEFF" # => false
```

**Comment by ntkme** [comment]
> charset (Boolean) — By default, if the CSS document contains non-ASCII characters, Sass adds a `@charset` declaration (in expanded output mode) or a byte-order mark (in compressed mode) to indicate its encoding to browsers or other consumers. If charset is false, these annotations are omitted.
