### ISSUE TITLE
Install in Debian broken - missing "x86_64-linux" version

### ISSUE THREAD

**Issue by djpremier** [sass-contrib/sass-embedded-host-ruby#269]
Hi,

The platform reported in Debian is "x86_64-linux", that not has a version in gem, so the bundle try install "x86_64-linux-musl" but this broken because not has "musl".

I'm using the Rails official docker image: `ghcr.io/rails/devcontainer/images/ruby:3.2.6`

```sh
$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```sh
$ ruby --version
ruby 3.2.6 (2024-10-30 revision 63aeb018eb) [x86_64-linux]
```

```sh
$ bundle platform
Your platform is: x86_64-linux

Your app has gems that work on these platforms:
* x86_64-linux
* x86_64-linux-musl

Your Gemfile specifies a Ruby version requirement:
* ruby 3.2.6

Your current platform satisfies the Ruby version requirement.
```

**Comment by ntkme** [comment]
This is a bug in Debian that nothing can be done here. I would recommend not using the ruby provided by Debian and instead installing your own ruby. See the following issues:

https://github.com/sass-contrib/sass-embedded-host-ruby/issues/176
https://github.com/jekyll/jekyll/issues/9478#issuecomment-1785797746

**Comment by ntkme** [comment]
Or, if it’s not Debian’s ruby, your are using a very old version of rubygems/bundler that perhaps need to be upgraded.
